## Importation des librairies et transformation des données

In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
#Chargement du dataframe
df_customer = pd.read_csv('shopping_test.csv', sep=";")

#On regroupe notre dataframe en fonction des colonnes Age, Gender, Location, Subscription Status, Frequency of Purchases
df_customer_info_grouped = df_customer.groupby(['Age','Gender', 'Location', 'Subscription Status','Frequency of Purchases'])

#On regroupe les produits achetés par les clients
aggregated_product = df_customer_info_grouped['Item Purchased'].apply(lambda x: ', '.join(x)).reset_index()

#On créer notre dataframe correspondant au regroupement des produits achetés par les clients
df_grouped_customer_purchase = pd.DataFrame(aggregated_product)

print("Aggregated product")
print(df_grouped_customer_purchase)
print("valeurs unique de produite", df_grouped_customer_purchase['Item Purchased'].nunique())
df_grouped_customer_purchase.to_csv('grouped_customer_purchase.csv', sep=';', index=False)

Aggregated product
      Age  Gender    Location Subscription Status Frequency of Purchases  \
0      18  Female      Alaska                  No                 Weekly   
1      18  Female    Illinois                  No            Fortnightly   
2      18  Female      Kansas                  No               Annually   
3      18  Female    Kentucky                  No            Fortnightly   
4      18  Female    Maryland                  No               Annually   
...   ...     ...         ...                 ...                    ...   
3744   70    Male       Texas                  No         Every 3 Months   
3745   70    Male       Texas                 Yes                Monthly   
3746   70    Male     Vermont                  No                Monthly   
3747   70    Male     Vermont                 Yes               Annually   
3748   70    Male  Washington                 Yes              Bi-Weekly   

      Item Purchased  
0             Shorts  
1              Shirt  

## Création de la table des produits

In [13]:
#On récupère l'ensemble des valeurs unique des produits
u_products = df_grouped_customer_purchase['Item Purchased'].str.split(', ', expand = True).stack().unique()

#On créer un dictionnaire qui représente la table d'achats des produits
data = {}

#On modifie la valeur stocké si le client a acheté ce produit
for i, row in df_grouped_customer_purchase.iterrows():
    items = row['Item Purchased'].split(', ')
    for item in items:
        if item not in data:
            data[item] = [0] * len(df_grouped_customer_purchase)
        data[item][i] += 1
df_product_table = pd.DataFrame(data)


print(df_product_table)
df_product_table.to_csv('product_table.csv', sep=';', index=False)


      Shorts  Shirt  Socks  Coat  Dress  Boots  Handbag  Sunglasses  Hat  \
0          1      0      0     0      0      0        0           0    0   
1          0      1      0     0      0      0        0           0    0   
2          0      0      1     0      0      0        0           0    0   
3          0      0      0     1      0      0        0           0    0   
4          0      0      0     0      1      0        0           0    0   
...      ...    ...    ...   ...    ...    ...      ...         ...  ...   
3744       0      0      0     0      0      0        0           0    0   
3745       0      0      0     0      0      0        0           0    0   
3746       0      0      0     0      0      0        0           0    0   
3747       0      0      0     0      0      0        0           0    0   
3748       0      0      0     0      0      0        0           0    0   

      Belt  ...  Sneakers  Sweater  Pants  T-shirt  Jewelry  Skirt  Blouse  \
0        

## Encodage des données

In [14]:
#Indexe des colonnes catégorielles (Gender,Location, Subscription Status, Frequency of Purchases)
cols_cat_info = [1,2,3,4]

#On créer une copie de notre dataframe source
df_grouped_customer = df_grouped_customer_purchase.copy()

#On supprime la colonne des achats
df_grouped_customer = df_grouped_customer.drop(columns=['Item Purchased'])
a_grouped_customer = df_grouped_customer.values
#Encodage des colonnes catégorielles
label_encoders_info = [LabelEncoder() for _ in range(len(cols_cat_info))]
for i, col_idx in enumerate(cols_cat_info):
    a_grouped_customer[:, col_idx] = label_encoders_info[i].fit_transform(a_grouped_customer[:, col_idx])
    
#Print des données encodées
print(a_grouped_customer)


[[18 0 1 0 6]
 [18 0 12 0 3]
 [18 0 15 0 0]
 ...
 [70 1 44 0 4]
 [70 1 44 1 0]
 [70 1 46 1 1]]


## Initialisation du modèle

In [15]:
from sklearn.multioutput import RegressorChain
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

a_product_table = df_product_table.values
#Initialisation du modèle
chained_model = RegressorChain(RandomForestRegressor(n_estimators=100, random_state=1), random_state=1)
chained_model.fit(a_grouped_customer, a_product_table)

y_pred = chained_model.predict(a_grouped_customer)
print("MSE : ",mean_squared_error(a_product_table, y_pred))
print(y_pred[0])

MSE :  0.006184065084022406
[0.71 0.12 0.02 0.01 0.   0.06 0.02 0.01 0.   0.04 0.01 0.04 0.02 0.
 0.02 0.03 0.   0.   0.01 0.02 0.03 0.07 0.   0.01 0.04]


In [16]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_validate, KFold
import numpy as np
import time

def run_regressor_chain_estimators(estimators, X, y):
    """
    Teste différents base estimators avec une RegressorChain et retourne les scores.

    Args:
    - estimators: Dictionnaire contenant les noms et les base estimators à tester.
    - X: Tableau NumPy des caractéristiques des clients.
    - y: Tableau NumPy des cibles (achats de produits).

    Returns:
    - best_estimator: Meilleur base estimator obtenu avec le score correspondant.
    """

    all_scores = []

    kf = KFold(n_splits=10, shuffle=True, random_state=0)
    for clf_name, clf in estimators.items():
        start = time.time()

        # Créez le modèle RegressorChain avec le base_estimator actuel et spécifiez le nombre de folds
        chain = RegressorChain(base_estimator=clf, cv=2, random_state=1)

        # Effectuez la validation croisée
        cv_results = cross_validate(chain, X, y, scoring='neg_mean_squared_error', return_train_score=False, cv=kf, n_jobs=-1)

        end = time.time()

        # Stockez les résultats dans all_scores
        all_scores.append([clf, np.mean(cv_results['test_score']), np.mean(cv_results['fit_time'])])
        
        # Affichez les résultats pour le modèle actuel
        print(f"Base estimator: {clf_name}")
        print(f"Mean MSE : {np.mean(cv_results['test_score']):.3f}")
        print(f"Mean fit time: {np.mean(cv_results['fit_time']):.3f} seconds")
        print("\n")
        print(cv_results)

    # Trouvez le meilleur base estimator en fonction du score moyen
    all_scores.sort(key=lambda x: x[1])
    best_estimator = all_scores[0][0]
    best_score = all_scores[0][1]
    best_fit_time = all_scores[0][2]

    print("Best base estimator is:", best_estimator)
    print("with a mean MSE of =", best_score)
    print("and a mean fit time of =", best_fit_time, "seconds")

    return best_estimator

In [17]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

# Liste des base estimators à tester
base_estimators = {
    'RandomForestRegressor': RandomForestRegressor(n_estimators=100,random_state=1, max_depth=5),
    'LinearRegression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(random_state=1),
    'ElasticNet': ElasticNet(random_state=1),
    'SVR': SVR(),
    'KNeighborsRegressor': KNeighborsRegressor(n_neighbors=5),
    'DecisionTreeRegressor': DecisionTreeRegressor(random_state=1),
    'XGBRegressor': XGBRegressor(n_estimators=100,random_state=1),
    'GradientBoostingRegressor': GradientBoostingRegressor(n_estimators=100,random_state=1),
}

# Utilisez la fonction run_regressor_chain_estimators avec la liste de base estimators
best_estimator = run_regressor_chain_estimators(base_estimators, a_grouped_customer, a_product_table)


Base estimator: RandomForestRegressor
Mean MSE : -0.045
Mean fit time: 68.626 seconds


{'fit_time': array([68.98167968, 70.88837028, 70.16626048, 69.75191045, 70.09209394,
       60.27919364, 67.33546567, 69.82360458, 70.6873889 , 68.25504947]), 'score_time': array([0.11045456, 0.09199047, 0.08787465, 0.08673143, 0.10840678,
       0.14047551, 0.11700511, 0.11693692, 0.08990097, 0.10677767]), 'test_score': array([-0.04074342, -0.04395035, -0.04158868, -0.04482652, -0.04122477,
       -0.05303707, -0.04254785, -0.05326962, -0.04119432, -0.04451518])}
Base estimator: LinearRegression
Mean MSE : -0.041
Mean fit time: 0.130 seconds


{'fit_time': array([0.08318233, 0.08338928, 0.14168119, 0.14617038, 0.14316416,
       0.14065433, 0.13865662, 0.14526391, 0.14318633, 0.13355923]), 'score_time': array([0.00150585, 0.00251102, 0.0040071 , 0.00310016, 0.00460124,
       0.00410247, 0.00410247, 0.00300217, 0.00300097, 0.00410581]), 'test_score': array([-0.04040399, -0.04078246, -0.04063861, -0

Utiliser Ridge/Lasso/ElasticNet